name: View Context Attributes

on:
  workflow_dispatch

jobs:
  view_context_attributes:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)
